import { Path } from '../Components/Navbar/types';

export const ACCENT_COLOR = 'rgba(64, 165, 228, 1)';

export enum TRANSLATION_KEYS {
	LinkAbout = `link-${Path.About}`,
	LinkEducation = `link-${Path.Education}`,
	LinkExperience = `link-${Path.Experience}`,
	LinkSkills = `link-${Path.Skills}`,
	LinkProjects = `link-${Path.Projects}`,
	LinkContacts = `link-${Path.Contacts}`,

	ContactMe = 'general-contact-me',

	IntroHiIAmName = 'intro-hi-i-am-name',
	IntroFrontendDeveloper = 'intro-frontend-developer',
	IntroMotivation = 'intro-motivation',
	IntroFooterItem_1 = 'intro-footer-item-1',
	IntroFooterItem_2 = 'intro-footer-item-2',
	IntroFooterItem_3 = 'intro-footer-item-3',
	IntroFooterItem_4 = 'intro-footer-item-4',
	IntroFooterItem_5 = 'intro-footer-item-5',
	IntroFooterItem_6 = 'intro-footer-item-6',

	AboutGreetingItem_1 = 'about-greeting-item-1',
	AboutGreetingItem_2 = 'about-greeting-item-2',
	AboutDescriptionItem_1 = 'about-description-item-1',
	AboutDescriptionItem_2 = 'about-description-item-2',
	AboutDescriptionItem_3 = 'about-description-item-3',
	AboutDescriptionItem_4 = 'about-description-item-4',
	AboutDescriptionItem_1_short = 'about-description-item-1_short',
	AboutDescriptionItem_2_short = 'about-description-item-2_short',
	AboutDescriptionItem_3_short = 'about-description-item-3_short',
	AboutDescriptionItem_4_short = 'about-description-item-4_short',
	AboutStandard = 'about-standard',

	EducationYears_1 = 'education-years-1',
	EducationYears_2 = 'education-years-2',
	EducationYears_3 = 'education-years-3',
	EducationTitle_1 = 'education-title-1',
	EducationTitle_2 = 'education-title-2',
	EducationTitle_3 = 'education-title-3',
	EducationDescription_1 = 'education-description-1',
	EducationDescription_2 = 'education-description-2',
	EducationDescription_3_1 = 'education-description-3-1',
	EducationDescription_3_2 = 'education-description-3-2',
	EducationCoreSkillsTitle = 'education-core-skills-title',
	EducationCoreSkills_1 = 'education-core-skills-1',

	EducationCoreSkills_2 = 'education-core-skills-2',

	SkillsType_1 = 'skill-type-1',
	SkillsType_2 = 'skill-type-2',
	SkillsType_3 = 'skill-type-3',
	SkillsType_1_GroupTitle_1 = 'skill-type-1-group-title-1',
	SkillsType_1_GroupTitle_2 = 'skill-type-1-group-title-2',
	SkillsType_1_GroupTitle_3 = 'skill-type-1-group-title-3',
	SkillsType_1_GroupTitle_4 = 'skill-type-1-group-title-4',
	SkillsType_1_GroupTitle_5 = 'skill-type-1-group-title-5',
	SkillsType_1_Group_1_Item_1 = 'skill-type-1-group-1-item-1',
	SkillsType_1_Group_1_Item_2 = 'skill-type-1-group-1-item-2',
	SkillsType_1_Group_1_Item_3 = 'skill-type-1-group-1-item-3',
	SkillsType_1_Group_2_Item_1 = 'skill-type-1-group-2-item-1',
	SkillsType_1_Group_2_Item_2 = 'skill-type-1-group-2-item-2',
	SkillsType_1_Group_2_Item_3 = 'skill-type-1-group-2-item-3',
	SkillsType_1_Group_2_Item_4 = 'skill-type-1-group-2-item-4',
	SkillsType_1_Group_2_Item_5 = 'skill-type-1-group-2-item-5',
	SkillsType_1_Group_3_Item_1 = 'skill-type-1-group-3-item-1',
	SkillsType_1_Group_3_Item_2 = 'skill-type-1-group-3-item-2',
	SkillsType_1_Group_3_Item_3 = 'skill-type-1-group-3-item-3',
	SkillsType_1_Group_3_Item_4 = 'skill-type-1-group-3-item-4',
	SkillsType_1_Group_3_Item_5 = 'skill-type-1-group-3-item-5',
	SkillsType_1_Group_4_Item_1 = 'skill-type-1-group-4-item-1',
	SkillsType_1_Group_4_Item_2 = 'skill-type-1-group-4-item-2',
	SkillsType_1_Group_5_Item_1 = 'skill-type-1-group-5-item-1',
	SkillsType_1_Group_5_Item_2 = 'skill-type-1-group-5-item-2',
	SkillsType_1_Group_5_Item_3 = 'skill-type-1-group-5-item-3',
	SkillsType_1_Group_5_Item_4 = 'skill-type-1-group-5-item-4',
	SkillsType_1_Group_5_Item_5 = 'skill-type-1-group-5-item-5',
	SkillsType_2_Item_1 = 'skill-type-2-item-1',
	SkillsType_2_Item_2 = 'skill-type-2-item-2',
	SkillsType_2_Item_3 = 'skill-type-2-item-3',
	SkillsType_2_Item_4 = 'skill-type-2-item-4',
	SkillsType_2_Item_5 = 'skill-type-2-item-5',
	SkillsType_2_Item_6 = 'skill-type-2-item-6',
	SkillsType_2_Item_7 = 'skill-type-2-item-7',
	SkillsType_3_Item_1 = 'skill-type-3-item-1',
	SkillsType_3_Item_2 = 'skill-type-3-item-2',
	SkillsType_3_Item_3 = 'skill-type-3-item-3',
	SkillsMessage = 'skill-message',
}

export enum ELEMENT_IDS {
	Logo = 'logo',
	LanguageButton = 'language_button',
	ContactMe = 'contact_me',
	IntroTypeIt = 'intro_type_it',
	SectionIntro = 'intro',
	MotivationWrapper = 'motivation_wrapper',
	IntroImage1 = 'intro_image_1',
	IntroImage2 = 'intro_image_2',
	IntroFooter = 'intro_footer',
	IntroHand = 'intro_hand',
	SectionAbout = 'about',
	SectionEducation = 'education',
	SectionExperience = 'experience',
	SectionSkills = 'skills',
	SectionContacts = 'contacts',
	SectionProjects = 'projects',
}
